trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Frontend
    displayName: Build Frontend
    jobs:
      - job: BuildReact
        displayName: React Vite Build
        steps:
          - task: UseNode@1
            inputs:
              version: '22.x'
            displayName: Install Node.js

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: Install and Build React

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'frontend/dist'
              ArtifactName: 'frontend-dist'
            displayName: Publish Frontend Artifact

  - stage: Backend
    displayName: Build Backend
    dependsOn: Frontend
    jobs:
      - job: BuildSpringBoot
        displayName: Spring Boot Build
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled
            displayName: Install Java 17

          - script: |
              cd backend
              ./mvnw clean package -DskipTests
            displayName: Maven Build

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'backend/target'
              ArtifactName: 'backend-jar'
            displayName: Publish Backend Artifact

  - stage: DeployBackend
    displayName: Deploy Backend
    dependsOn: Backend
    jobs:
      - job: DeploySpringBoot
        displayName: Deploy to Azure App Service
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: current
              artifactName: 'backend-jar'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: Deploy Backend to App Service
            inputs:
              azureSubscription: 'Azure for Students'
              appType: webAppLinux
              appName: 'college-carnival-backend'
              package: '$(System.ArtifactsDirectory)/backend-jar/*.jar'
              runtimeStack: 'JAVA|17-java17'

  - stage: DeployFrontend
    displayName: Deploy Frontend
    dependsOn: DeployBackend
    jobs:
      - job: DeployReact
        displayName: Deploy to Azure App Service
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: current
              artifactName: 'frontend-dist'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: Deploy Frontend to App Service
            inputs:
              azureSubscription: 'Azure for Students'
              appType: webAppLinux
              appName: 'college-carnival-frontend'
              package: '$(System.ArtifactsDirectory)/frontend-dist'
              runtimeStack: 'NODE|22-lts'